BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'vertical'
        # this layout is populated with Button labels in app code
        id: entries_box
    Label:
        size_hint_y: 0.1
        text: app.status_text
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.2
        Button:
            text: "Create labels"
            on_release: app.create_labels()
        Button:
            text: "Clear labels"
            on_release: app.clear_all()